import React, { useState, useEffect } from 'react';
import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    ScrollView,
    StatusBar,
    Alert,
    Linking,
    Image
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as Location from 'expo-location';
import { useAppStore } from '../src/store/useAppStore';

const NAVY = '#003366';
const YELLOW = '#FACC15';
const BG = '#F5F7FA';
const WHITE = '#FFFFFF';
const GRAY = '#6B7280';
const BORDER = '#E5E7EB';

export default function DriverActiveDeliveryScreen() {
    const router = useRouter();
    const insets = useSafeAreaInsets();
    const { activeDriverOrder, updateDriverOrderStatus } = useAppStore();

    // ── Dynamic Reverse Geocoding ───────────────────────────────────────────────
    const [dynamicAddress, setDynamicAddress] = useState('Locating...');

    useEffect(() => {
        (async () => {
            try {
                const { status } = await Location.requestForegroundPermissionsAsync();
                if (status !== 'granted') {
                    setDynamicAddress('2.5 km away - Local Delivery');
                    return;
                }
                const location = await Location.getCurrentPositionAsync({});
                const destLat = location.coords.latitude + 0.022;
                const destLng = location.coords.longitude + 0.022;

                // Use OpenStreetMap Nominatim — free, no API key, works on web & mobile
                const res = await fetch(
                    `https://nominatim.openstreetmap.org/reverse?lat=${destLat}&lon=${destLng}&format=json`,
                    { headers: { 'Accept-Language': 'en', 'User-Agent': 'AmmarliApp/1.0' } }
                );
                if (res.ok) {
                    const data = await res.json();
                    const place =
                        data?.address?.city ||
                        data?.address?.town ||
                        data?.address?.village ||
                        data?.address?.state ||
                        'Algeria';
                    setDynamicAddress('2.5 km away - ' + place);
                } else {
                    setDynamicAddress('2.5 km away - Local Delivery');
                }
            } catch {
                setDynamicAddress('2.5 km away - Local Delivery');
            }
        })();
    }, []);

    // Mock data matching the UI precisely
    const order = activeDriverOrder || {
        orderId: '84291',
        customer: { name: 'Ahmed Benali', phone: '+213 555 12 34 56' },
        deliveryAddress: { label: 'Batna, Algeria', distance: '2.5 km away' },
        items: [{ icon: 'cube', description: '5x 1.5L Packs (Ifri)', detail: 'Mineral Water', price: 1100 }],
        subtotal: 1100, deliveryFee: 150, total: 1250,
        createdAt: 'Oct 24, 2023 - 14:20'
    };

    const handleComplete = () => {
        updateDriverOrderStatus('completed');
        router.replace('/driver-invoice');
    };

    // ── Live GPS Route Implementation ──────────────────────────────────────────
    const openLiveGoogleMaps = async () => {
        try {
            // Request foreground permission
            const { status } = await Location.requestForegroundPermissionsAsync();
            if (status !== 'granted') {
                Alert.alert('Permission Denied', 'Location permission is required to calculate the route.');
                return;
            }

            // ① Get the driver's REAL current position (origin — changes with every GPS location)
            const loc = await Location.getCurrentPositionAsync({});
            const originLat = loc.coords.latitude;
            const originLng = loc.coords.longitude;

            // ② Use the EXACT destination stored in the order
            //    (these coords were generated by generateSmartOrder at order-creation time)
            let destLat: number;
            let destLng: number;

            if (activeDriverOrder?.deliveryAddress?.lat && activeDriverOrder?.deliveryAddress?.lng) {
                destLat = activeDriverOrder.deliveryAddress.lat;
                destLng = activeDriverOrder.deliveryAddress.lng;
            } else {
                // Fallback for mock data only
                destLat = originLat + 0.022;
                destLng = originLng + 0.022;
            }

            // Both origin and destination change dynamically with GPS
            const url =
                `https://www.google.com/maps/dir/?api=1` +
                `&origin=${originLat},${originLng}` +
                `&destination=${destLat},${destLng}` +
                `&travelmode=driving`;

            Linking.openURL(url).catch(() =>
                Alert.alert('Error', 'Could not open Google Maps app.')
            );
        } catch (error) {
            Alert.alert('Location Error', 'Failed to retrieve your current location.');
        }
    };

    const callCustomer = () => {
        const phone = order.customer.phone.replace(/\s/g, '');
        Linking.openURL(`tel:${phone}`).catch(() =>
            Alert.alert('Error', 'Could not open phone dialer.')
        );
    };


    // ── Main Layout ────────────────────────────────────────────────────────────
    return (
        <View style={[styles.root, { paddingBottom: 0 }]}>
            <StatusBar barStyle="dark-content" />

            {/* Header */}
            <View style={[styles.header, { paddingTop: insets.top + 16 }]}>
                <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
                    <Ionicons name="chevron-back" size={24} color={NAVY} />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Order Details</Text>
                <View style={{ width: 40 }} />
            </View>

            <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
                
                {/* ── TOP NAVY CARD ── */}
                <View style={styles.topCard}>
                    {/* Background Graphic */}
                    <View style={styles.topCardCircle} />
                    
                    <View style={styles.topCardHeaderRow}>
                        <View>
                            <Text style={styles.topCardLabel}>Order ID</Text>
                            <Text style={styles.topCardId}>#{order.orderId}</Text>
                        </View>
                        <View style={styles.inProgressBadge}>
                            <Text style={styles.inProgressText}>IN PROGRESS</Text>
                        </View>
                    </View>
                    <View style={styles.topCardDateRow}>
                        <Ionicons name="calendar-outline" size={14} color="#CBD5E1" />
                        <Text style={styles.topCardDate}> {order.createdAt}</Text>
                    </View>
                </View>

                {/* ── CUSTOMER INFO ── */}
                <Text style={styles.sectionTitle}>CUSTOMER INFORMATION</Text>
                <View style={styles.whiteCard}>
                    <View style={styles.cardRow}>
                        <View style={styles.avatarWrap}>
                            <Image 
                                source={{ uri: 'https://randomuser.me/api/portraits/men/32.jpg' }} 
                                style={{ width: 48, height: 48, borderRadius: 24 }} 
                            />
                        </View>
                        <View style={{ marginLeft: 16 }}>
                            <Text style={styles.boldNavyText}>{order.customer.name}</Text>
                            <Text style={styles.graySubText}>{order.customer.phone}</Text>
                        </View>
                    </View>
                </View>

                {/* ── ADDRESS SECTION ── */}
                <TouchableOpacity activeOpacity={0.8} onPress={openLiveGoogleMaps} style={styles.whiteCard}>
                    <View style={styles.cardRow}>
                        <View style={styles.mapIconBox}>
                            <Ionicons name="map" size={20} color={NAVY} />
                        </View>
                        <View style={{ marginLeft: 16 }}>
                            <Text style={styles.boldNavyText}>Delivery Address</Text>
                            <Text style={styles.graySubText}>{dynamicAddress}</Text>
                        </View>
                    </View>
                </TouchableOpacity>

                {/* ── MAP PREVIEW ── */}
                <TouchableOpacity activeOpacity={0.85} onPress={openLiveGoogleMaps} style={styles.mapPreviewWrap}>
                    <Image 
                        source={{ uri: 'https://i.stack.imgur.com/Kzpw7.png' }} 
                        style={styles.mapImage}
                        resizeMode="cover"
                        blurRadius={1}
                    />
                    <View style={styles.mapOverlayCenterMarker}>
                        <View style={styles.markerCircle}>
                            <Ionicons name="location" size={20} color={NAVY} />
                        </View>
                    </View>
                </TouchableOpacity>

                {/* ── ORDER ITEMS ── */}
                <Text style={styles.sectionTitle}>ORDER ITEMS</Text>
                <View style={styles.whiteCard}>
                    {order.items.map((item, i) => (
                        <View key={i} style={[styles.cardRow, { marginBottom: 24, alignItems: 'center' }]}>
                            <View style={styles.itemIconBox}>
                                <Ionicons name={item.icon as any} size={22} color={NAVY} />
                            </View>
                            <View style={{ flex: 1, marginLeft: 16 }}>
                                <Text style={styles.boldNavyText}>{item.description}</Text>
                                <Text style={styles.graySubText}>{item.detail}</Text>
                            </View>
                            <Text style={styles.itemPriceText}>{item.price.toLocaleString()} DA</Text>
                        </View>
                    ))}

                    {/* Breakdown */}
                    <View style={styles.breakdownRow}>
                        <Text style={styles.graySubText}>Subtotal</Text>
                        <Text style={styles.graySubText}>{order.subtotal.toLocaleString()} DA</Text>
                    </View>
                    <View style={styles.breakdownRow}>
                        <Text style={styles.graySubText}>Delivery Fee</Text>
                        <Text style={styles.graySubText}>{order.deliveryFee.toLocaleString()} DA</Text>
                    </View>

                    <View style={styles.divider} />

                    <View style={[styles.breakdownRow, { marginBottom: 0 }]}>
                        <Text style={styles.totalLabel}>Total Amount</Text>
                        <Text style={styles.totalAmount}>{order.total.toLocaleString()} DA</Text>
                    </View>
                </View>

            </ScrollView>

            {/* ── BOTTOM ACTIONS ── */}
            <View style={[styles.bottomActionBar, { paddingBottom: Math.max(insets.bottom, 24) }]}>
                <TouchableOpacity style={styles.callOutlinedBtn} onPress={callCustomer} activeOpacity={0.8}>
                    <Ionicons name="call" size={18} color={NAVY} />
                    <Text style={styles.callOutlinedText}>Call Customer</Text>
                </TouchableOpacity>

                <TouchableOpacity style={styles.completeSolidBtn} onPress={handleComplete} activeOpacity={0.8}>
                    <Ionicons name="checkmark-circle" size={20} color={NAVY} />
                    <Text style={styles.completeSolidText}>Complete Delivery</Text>
                </TouchableOpacity>

                <TouchableOpacity
                    style={styles.cancelLinkBtn}
                    onPress={() => router.push('/driver-decline-order')}
                    activeOpacity={0.7}
                >
                    <Text style={styles.cancelLinkText}>Cancel Order</Text>
                </TouchableOpacity>
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    root: { flex: 1, backgroundColor: BG },
    
    // Header
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingBottom: 16,
        backgroundColor: BG,
    },
    backBtn: { width: 40, height: 40, justifyContent: 'center' },
    headerTitle: { fontSize: 18, fontWeight: '800', color: NAVY },

    scroll: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 180 },

    // Top Card
    topCard: {
        backgroundColor: NAVY,
        borderRadius: 24,
        padding: 24,
        marginBottom: 24,
        overflow: 'hidden',
        position: 'relative'
    },
    topCardCircle: {
        position: 'absolute',
        bottom: -40, right: -20,
        width: 140, height: 140,
        borderRadius: 70,
        backgroundColor: '#1E40AF', // slightly lighter navy for graphic
        opacity: 0.5
    },
    topCardHeaderRow: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start',
        marginBottom: 16
    },
    topCardLabel: { fontSize: 12, color: '#94A3B8', fontWeight: '600', letterSpacing: 0.5 },
    topCardId: { fontSize: 28, fontWeight: '900', color: WHITE, marginTop: 2 },
    inProgressBadge: { backgroundColor: YELLOW, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16 },
    inProgressText: { fontSize: 10, fontWeight: '800', color: NAVY, letterSpacing: 1 },
    topCardDateRow: { flexDirection: 'row', alignItems: 'center' },
    topCardDate: { fontSize: 13, color: '#CBD5E1', marginLeft: 4, fontWeight: '500' },

    // Sections
    sectionTitle: {
        fontSize: 12, fontWeight: '800', color: NAVY, letterSpacing: 1,
        marginBottom: 12, marginLeft: 4, textTransform: 'uppercase'
    },
    whiteCard: {
        backgroundColor: WHITE,
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
    },
    cardRow: { flexDirection: 'row', alignItems: 'center' },
    avatarWrap: {
        width: 48, height: 48, borderRadius: 24,
        backgroundColor: '#E2E8F0', justifyContent: 'center', alignItems: 'center'
    },
    mapIconBox: {
        width: 48, height: 48, borderRadius: 16,
        backgroundColor: '#E2E8F0', justifyContent: 'center', alignItems: 'center'
    },
    itemIconBox: {
        width: 48, height: 48, borderRadius: 16,
        backgroundColor: '#F1F5F9', justifyContent: 'center', alignItems: 'center'
    },
    boldNavyText: { fontSize: 16, fontWeight: 'bold', color: NAVY, marginBottom: 2 },
    graySubText: { fontSize: 14, color: GRAY },
    itemPriceText: { fontSize: 16, fontWeight: '800', color: NAVY },

    // Map Preview
    mapPreviewWrap: {
        width: '100%',
        height: 160,
        borderRadius: 24,
        overflow: 'hidden',
        marginBottom: 24,
        backgroundColor: '#E2E8F0', // fallback
        justifyContent: 'center', alignItems: 'center'
    },
    mapImage: {
        ...StyleSheet.absoluteFillObject,
        opacity: 0.8
    },
    mapOverlayCenterMarker: {
        width: 60, height: 60, borderRadius: 30,
        backgroundColor: 'rgba(255,255,255,0.7)',
        justifyContent: 'center', alignItems: 'center'
    },
    markerCircle: {
        width: 40, height: 40, borderRadius: 20,
        backgroundColor: WHITE,
        justifyContent: 'center', alignItems: 'center',
        shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8, elevation: 5
    },

    // Breakdown Pricing
    breakdownRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
    divider: { height: 1, backgroundColor: BORDER, marginVertical: 16 },
    totalLabel: { fontSize: 16, fontWeight: '800', color: NAVY },
    totalAmount: { fontSize: 20, fontWeight: '900', color: NAVY },

    // Actions
    bottomActionBar: {
        position: 'absolute', bottom: 0, left: 0, right: 0,
        backgroundColor: BG,
        paddingHorizontal: 20,
        paddingTop: 8,
        gap: 12
    },
    callOutlinedBtn: {
        flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8,
        borderWidth: 2, borderColor: NAVY, borderRadius: 20,
        paddingVertical: 16, width: '100%'
    },
    callOutlinedText: { fontSize: 16, fontWeight: 'bold', color: NAVY },
    completeSolidBtn: {
        flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8,
        backgroundColor: YELLOW, borderRadius: 20,
        paddingVertical: 18, width: '100%',
        shadowColor: YELLOW, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4
    },
    completeSolidText: { fontSize: 16, fontWeight: 'bold', color: NAVY },
    cancelLinkBtn: { alignItems: 'center', paddingVertical: 4 },
    cancelLinkText: { fontSize: 14, fontWeight: '600', color: GRAY, textDecorationLine: 'underline' },
});
